-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-04-15 22:20:04 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c


-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE blog
(
    id           INTEGER NOT NULL,
    content      VARCHAR2(4096 CHAR),
    image        BLOB,
    createdat    DATE,
    createdby    INTEGER,
    lastupdateat DATE,
    lastupdateby INTEGER
);

ALTER TABLE blog
    ADD CONSTRAINT blog_pk PRIMARY KEY (id);

CREATE TABLE contact
(
    id      INTEGER NOT NULL,
    content VARCHAR2(2048),
    name    VARCHAR2(128),
    surname VARCHAR2(128 CHAR),
    phone   VARCHAR2(12 CHAR),
    email   VARCHAR2(128 CHAR),
    status  VARCHAR2(128 CHAR)
);

ALTER TABLE contact
    ADD CONSTRAINT contact_pk PRIMARY KEY (id);

CREATE TABLE course
(
    id          INTEGER NOT NULL,
    name        VARCHAR2(64 CHAR),
    description VARCHAR2(64 CHAR),
    duration    INTERVAL DAY (9) TO SECOND (0),
    category    VARCHAR2(64 CHAR)
);

ALTER TABLE course
    ADD CONSTRAINT course_pk PRIMARY KEY (id);

CREATE TABLE drivinglesson
(
    id        INTEGER NOT NULL,
    starttime DATE,
    endtime   DATE,
    time      INTERVAL DAY (9) TO SECOND (0),
    userid    INTEGER NOT NULL,
    studentid INTEGER,
    status    VARCHAR2(128 CHAR)
);

ALTER TABLE drivinglesson
    ADD CONSTRAINT drivinglesson_pk PRIMARY KEY (id);

CREATE TABLE exam
(
    id             INTEGER NOT NULL,
    name           VARCHAR2(128 CHAR),
    points         INTEGER,
    questionnumber INTEGER
);

ALTER TABLE exam
    ADD CONSTRAINT exam_pk PRIMARY KEY (id);

CREATE TABLE lecture
(
    id   INTEGER NOT NULL,
    name VARCHAR2(128) NOT NULL
);

ALTER TABLE lecture
    ADD CONSTRAINT lecture_pk PRIMARY KEY (id);

CREATE TABLE lecturemeeting
(
    id        INTEGER NOT NULL,
    starttime DATE,
    endtime   DATE,
    subject   VARCHAR2(128 CHAR),
    userid    INTEGER NOT NULL,
    status    VARCHAR2(64 CHAR)
);

ALTER TABLE lecturemeeting
    ADD CONSTRAINT lecturemeeting_pk PRIMARY KEY (id);

CREATE TABLE payment
(
    payment INTEGER NOT NULL,
    id      INTEGER NOT NULL,
    userid  INTEGER NOT NULL
);

ALTER TABLE payment
    ADD CONSTRAINT payment_pk PRIMARY KEY (id);

CREATE TABLE question
(
    id                INTEGER NOT NULL,
    question          VARCHAR2(512 CHAR),
    answera           VARCHAR2(512 CHAR),
    answerb           VARCHAR2(512 CHAR),
    answerc           VARCHAR2(512 CHAR),
    availablequestion INTEGER,
    correctanswer     INTEGER,
    medianame         VARCHAR2(512 CHAR),
    explanation       VARCHAR2(1024 CHAR),
    questiontype      VARCHAR2(512 CHAR),
    category          VARCHAR2(128 CHAR),
    testid            INTEGER NOT NULL
);

ALTER TABLE question
    ADD CONSTRAINT question_pk PRIMARY KEY (id);

CREATE TABLE questionset
(
    examid     INTEGER NOT NULL,
    questionid INTEGER NOT NULL
);

ALTER TABLE questionset
    ADD CONSTRAINT questionset_pk PRIMARY KEY (examid,
                                               questionid);

CREATE TABLE role
(
    id       INTEGER NOT NULL,
    rolename VARCHAR2(64 CHAR)
);

ALTER TABLE role
    ADD CONSTRAINT role_pk PRIMARY KEY (id);

CREATE TABLE sensitivedata
(
    id              INTEGER NOT NULL,
    address         VARCHAR2(64 CHAR),
    city            VARCHAR2(64 CHAR),
    streetnumber    INTEGER,
    apartmentnumber INTEGER,
    zipcode         VARCHAR2(64 CHAR),
    phonenumber     VARCHAR2(15 CHAR),
    email           VARCHAR2(64 CHAR),
    userid          INTEGER NOT NULL
);

CREATE UNIQUE INDEX sensitivedata__idx ON
    sensitivedata (
                   userid
                   ASC);

ALTER TABLE sensitivedata
    ADD CONSTRAINT sensitivedata_pk PRIMARY KEY (id);

CREATE TABLE servicestastic
(
    id                      INTEGER NOT NULL,
    numbersolvedexams       INTEGER,
    numberansweredquestions INTEGER,
    numberstudent           INTEGER,
    numbercategories        INTEGER,
    numberinstructors       INTEGER,
    createdat               DATE
);

ALTER TABLE servicestastic
    ADD CONSTRAINT servicestastic_pk PRIMARY KEY (id);

CREATE TABLE studentanswerstest
(
    answertype NUMBER,
    userid     INTEGER NOT NULL,
    questionid INTEGER NOT NULL,
    testid     INTEGER NOT NULL
);

ALTER TABLE studentanswerstest
    ADD CONSTRAINT studentanswerstest_pk PRIMARY KEY (userid,
                                                      questionid,
                                                      testid);

CREATE TABLE studentcourse
(
    userid    INTEGER NOT NULL,
    courseid  INTEGER NOT NULL,
    passed    NUMBER  NOT NULL,
    startedat DATE,
    endat     DATE
);

ALTER TABLE studentcourse
    ADD CONSTRAINT studentcourse_pk PRIMARY KEY (userid,
                                                 courseid);

CREATE TABLE studentexam
(
    id       INTEGER NOT NULL,
    category VARCHAR2(128 CHAR),
    points   INTEGER,
    examid   INTEGER NOT NULL,
    userid   INTEGER NOT NULL
);

ALTER TABLE studentexam
    ADD CONSTRAINT studentexam_pk PRIMARY KEY (id);

CREATE TABLE studentexamanswer
(
    questionid    INTEGER NOT NULL,
    answertype    NUMBER  NOT NULL,
    studentexamid INTEGER NOT NULL
);

ALTER TABLE studentexamanswer
    ADD CONSTRAINT studentexamanswer_pk PRIMARY KEY (questionid);

CREATE TABLE subject
(
    id           INTEGER NOT NULL,
    subject      VARCHAR2(512),
    name         VARCHAR2(5128),
    image        BLOB,
    sublectureid INTEGER NOT NULL
);

ALTER TABLE subject
    ADD CONSTRAINT subject_pk PRIMARY KEY (id);

CREATE TABLE sublecture
(
    id        INTEGER NOT NULL,
    title     VARCHAR2(128 CHAR),
    lectureid INTEGER NOT NULL
);

ALTER TABLE sublecture
    ADD CONSTRAINT sublecture_pk PRIMARY KEY (id);

CREATE TABLE test
(
    id             INTEGER NOT NULL,
    name           VARCHAR2(512 CHAR),
    numberquestion INTEGER,
    image          BLOB,
    questiontype   VARCHAR2(512 CHAR)
);

ALTER TABLE test
    ADD CONSTRAINT test_pk PRIMARY KEY (id);

CREATE TABLE "User"
(
    id            INTEGER NOT NULL,
    name          VARCHAR2(64 CHAR),
    surname       VARCHAR2(64 CHAR),
    password      VARCHAR2(256 CHAR),
    email         VARCHAR2(64 CHAR),
    createdat     DATE,
    createdby     VARCHAR2(64 CHAR),
    lastupdateat  DATE,
    lastupdatedat VARCHAR2(64 CHAR),
    roleid        INTEGER NOT NULL
);

CREATE UNIQUE INDEX user__idx ON
    "User" (
            roleid
            ASC);

ALTER TABLE "User"
    ADD CONSTRAINT user_pk PRIMARY KEY (id);

CREATE TABLE userstatistic
(
    id           INTEGER NOT NULL,
    deposits     INTEGER,
    isexampassed VARCHAR2(128 CHAR),
    hourused     INTERVAL DAY (9) TO SECOND (0),
    hoursbuyed   INTERVAL DAY (9) TO SECOND (0),
    userid       INTEGER NOT NULL
);

CREATE UNIQUE INDEX userstatistic__idx ON
    userstatistic (
                   userid
                   ASC);

ALTER TABLE userstatistic
    ADD CONSTRAINT userstatistic_pk PRIMARY KEY (id);

ALTER TABLE drivinglesson
    ADD CONSTRAINT drivinglesson_user_fk FOREIGN KEY (userid)
        REFERENCES "User" (id);

ALTER TABLE lecturemeeting
    ADD CONSTRAINT lecturemeeting_user_fk FOREIGN KEY (userid)
        REFERENCES "User" (id)
        ON DELETE CASCADE;

ALTER TABLE payment
    ADD CONSTRAINT payment_user_fk FOREIGN KEY (userid)
        REFERENCES "User" (id)
        ON DELETE CASCADE;

ALTER TABLE question
    ADD CONSTRAINT question_test_fk FOREIGN KEY (testid)
        REFERENCES test (id);

ALTER TABLE questionset
    ADD CONSTRAINT questionset_exam_fk FOREIGN KEY (examid)
        REFERENCES exam (id);

ALTER TABLE questionset
    ADD CONSTRAINT questionset_question_fk FOREIGN KEY (questionid)
        REFERENCES question (id);

ALTER TABLE sensitivedata
    ADD CONSTRAINT sensitivedata_user_fk FOREIGN KEY (userid)
        REFERENCES "User" (id)
        ON DELETE CASCADE;

ALTER TABLE studentanswerstest
    ADD CONSTRAINT studentanswerstest_question_fk FOREIGN KEY (questionid)
        REFERENCES question (id);

ALTER TABLE studentanswerstest
    ADD CONSTRAINT studentanswerstest_test_fk FOREIGN KEY (testid)
        REFERENCES test (id);

ALTER TABLE studentanswerstest
    ADD CONSTRAINT studentanswerstest_user_fk FOREIGN KEY (userid)
        REFERENCES "User" (id)
        ON DELETE CASCADE;

ALTER TABLE studentcourse
    ADD CONSTRAINT studentcourse_course_fk FOREIGN KEY (courseid)
        REFERENCES course (id);

ALTER TABLE studentcourse
    ADD CONSTRAINT studentcourse_user_fk FOREIGN KEY (userid)
        REFERENCES "User" (id)
        ON DELETE CASCADE;

ALTER TABLE studentexam
    ADD CONSTRAINT studentexam_exam_fk FOREIGN KEY (examid)
        REFERENCES exam (id);

ALTER TABLE studentexam
    ADD CONSTRAINT studentexam_user_fk FOREIGN KEY (userid)
        REFERENCES "User" (id)
        ON DELETE CASCADE;

ALTER TABLE studentexamanswer
    ADD CONSTRAINT studentexamanswer_question_fk FOREIGN KEY (questionid)
        REFERENCES question (id);

ALTER TABLE studentexamanswer
    ADD CONSTRAINT studentexamanswer_se_fk FOREIGN KEY (studentexamid)
        REFERENCES studentexam (id)
        ON DELETE CASCADE;

ALTER TABLE subject
    ADD CONSTRAINT subject_sublecture_fk FOREIGN KEY (sublectureid)
        REFERENCES sublecture (id)
        ON DELETE CASCADE;

ALTER TABLE sublecture
    ADD CONSTRAINT sublecture_lecture_fk FOREIGN KEY (lectureid)
        REFERENCES lecture (id)
        ON DELETE CASCADE;

ALTER TABLE "User"
    ADD CONSTRAINT user_role_fk FOREIGN KEY (roleid)
        REFERENCES role (id);

ALTER TABLE userstatistic
    ADD CONSTRAINT userstatistic_user_fk FOREIGN KEY (userid)
        REFERENCES "User" (id)
        ON DELETE CASCADE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            22
-- CREATE INDEX                             3
-- ALTER TABLE                             42
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
