-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-04-23 20:53:58 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c


-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

DROP TABLE blog;
DROP TABLE contact;
DROP TABLE course;
DROP TABLE drivingSession;
DROP TABLE lecture;
DROP TABLE lectureMeeting;
DROP TABLE payment;
DROP TABLE question;
DROP TABLE questionSet;
DROP TABLE schoolUser;
DROP TABLE sensitiveData;
DROP TABLE serviceStatistic;
DROP TABLE studentAnswersTest;
DROP TABLE studentCourse;
DROP TABLE studentExam;
DROP TABLE studentExamAnswer;
DROP TABLE subject;
DROP TABLE sublecture;
DROP TABLE test;
DROP TABLE userStatistic;
DROP TABLE exam;

CREATE TABLE blog
(
    id           INTEGER NOT NULL,
    content      VARCHAR2(3800 CHAR),
    image        BLOB,
    createdAt    DATE,
    createdBy    INTEGER,
    lastUpdatedAt DATE,
    lastUpdatedBy INTEGER
);

ALTER TABLE blog
    ADD CONSTRAINT blog_pk PRIMARY KEY (id);

CREATE TABLE contact
(
    id      INTEGER NOT NULL,
    content VARCHAR2(2048),
    name    VARCHAR2(128),
    surname VARCHAR2(128 CHAR),
    phone   VARCHAR2(12 CHAR),
    email   VARCHAR2(128 CHAR),
    status  VARCHAR2(128 CHAR)
);

ALTER TABLE contact
    ADD CONSTRAINT contact_pk PRIMARY KEY (id);

CREATE TABLE course
(
    id          INTEGER NOT NULL,
    name        VARCHAR2(64 CHAR),
    description VARCHAR2(64 CHAR),
    duration    INTERVAL DAY (9) TO SECOND (0),
    category    VARCHAR2(64 CHAR)
);

ALTER TABLE course
    ADD CONSTRAINT course_pk PRIMARY KEY (id);

CREATE TABLE drivingSession
(
    id            INTEGER NOT NULL,
    startTime     DATE,
    endTime       DATE,
    time          INTERVAL DAY (9) TO SECOND (0),
    schoolUserId INTEGER NOT NULL,
    studentId     INTEGER,
    status        VARCHAR2(128 CHAR)
);

ALTER TABLE drivingSession
    ADD CONSTRAINT drivinglesson_pk PRIMARY KEY (id);

CREATE TABLE exam
(
    id             INTEGER NOT NULL,
    name           VARCHAR2(128 CHAR),
    points         INTEGER,
    questionNumber INTEGER
);

ALTER TABLE exam
    ADD CONSTRAINT exam_pk PRIMARY KEY (id);

CREATE TABLE lecture
(
    id   INTEGER NOT NULL,
    name VARCHAR2(128) NOT NULL
);

ALTER TABLE lecture
    ADD CONSTRAINT lecture_pk PRIMARY KEY (id);

CREATE TABLE lectureMeeting
(
    id           INTEGER NOT NULL,
    startTime    DATE,
    endTime      DATE,
    subject      VARCHAR2(128 CHAR),
    schoolUserId INTEGER NOT NULL,
    status       VARCHAR2(64 CHAR)
);

ALTER TABLE lectureMeeting
    ADD CONSTRAINT lecturemeeting_pk PRIMARY KEY (id);

CREATE TABLE payment
(
    payment      INTEGER NOT NULL,
    id           INTEGER NOT NULL,
    schoolUserId INTEGER NOT NULL
);

ALTER TABLE payment
    ADD CONSTRAINT payment_pk PRIMARY KEY (id);

CREATE TABLE question
(
    id                INTEGER NOT NULL,
    question          VARCHAR2(512 CHAR),
    answerA           VARCHAR2(512 CHAR),
    answerB           VARCHAR2(512 CHAR),
    answerC           VARCHAR2(512 CHAR),
    availableQuestions INTEGER,
    correctAnswer     INTEGER,
    mediaName         VARCHAR2(512 CHAR),
    explanation       VARCHAR2(1024 CHAR),
    questionType      VARCHAR2(512 CHAR),
    category          VARCHAR2(128 CHAR),
    testId            INTEGER NOT NULL
);

ALTER TABLE question
    ADD CONSTRAINT question_pk PRIMARY KEY (id);

CREATE TABLE questionSet
(
    examId     INTEGER NOT NULL,
    questionId INTEGER NOT NULL
);

ALTER TABLE questionSet
    ADD CONSTRAINT questionset_pk PRIMARY KEY (examId,
                                               questionId);

CREATE TABLE schoolUser
(
    id            INTEGER NOT NULL,
    name          VARCHAR2(64 CHAR),
    surname       VARCHAR2(64 CHAR),
    password      VARCHAR2(256 CHAR),
    email         VARCHAR2(64 CHAR),
    createdAt     DATE,
    createdBy     VARCHAR2(64 CHAR),
    lastUpdatedAt  DATE,
    lastUpdatedBy VARCHAR2(64 CHAR),
    roleName      VARCHAR2(128 CHAR)
);

ALTER TABLE schoolUser
    ADD CONSTRAINT schooluser_pk PRIMARY KEY (id);

CREATE TABLE sensitiveData
(
    id              INTEGER NOT NULL,
    address         VARCHAR2(64 CHAR),
    city            VARCHAR2(64 CHAR),
    streetNumber    INTEGER,
    apartmentNumber INTEGER,
    zipCode         VARCHAR2(64 CHAR),
    phoneNumber     VARCHAR2(15 CHAR),
    email           VARCHAR2(64 CHAR),
    schoolUserId    INTEGER NOT NULL
);

CREATE UNIQUE INDEX sensitivedata__idx ON
    sensitiveData (
                   schoolUserId
                   ASC);

ALTER TABLE sensitiveData
    ADD CONSTRAINT sensitivedata_pk PRIMARY KEY (id);

CREATE TABLE serviceStatistic
(
    id                      INTEGER NOT NULL,
    numberSolvedExams       INTEGER,
    numberAnsweredQuestions INTEGER,
    numberStudent           INTEGER,
    numberCategories        INTEGER,
    numberInstructors       INTEGER,
    createdAt               DATE
);

ALTER TABLE serviceStatistic
    ADD CONSTRAINT servicestastic_pk PRIMARY KEY (id);

CREATE TABLE studentAnswersTest
(
    id           INTEGER NOT NULL,
    answerType   NUMBER,
    schoolUserId INTEGER NOT NULL,
    questionId   INTEGER NOT NULL,
    testId       INTEGER NOT NULL
);

ALTER TABLE studentAnswersTest
    ADD CONSTRAINT studentat_pk PRIMARY KEY (id);

CREATE TABLE studentCourse
(
    schoolUserId INTEGER NOT NULL,
    courseId    INTEGER NOT NULL,
    passed       NUMBER  NOT NULL,
    startedAt    DATE,
    endAt        DATE
);

ALTER TABLE studentCourse
    ADD CONSTRAINT studentcourse_pk PRIMARY KEY (schoolUserId,
                                                 courseId);

CREATE TABLE studentExam
(
    id           INTEGER NOT NULL,
    category     VARCHAR2(128 CHAR),
    points       INTEGER,
    examId       INTEGER NOT NULL,
    schoolUserId INTEGER NOT NULL
);

ALTER TABLE studentExam
    ADD CONSTRAINT studentexam_pk PRIMARY KEY (id);

CREATE TABLE studentExamAnswer
(
    answerType    NUMBER  NOT NULL,
    studentExamId INTEGER NOT NULL,
    questionId    INTEGER NOT NULL
);

ALTER TABLE studentExamAnswer
    ADD CONSTRAINT studentexamanswer_pk PRIMARY KEY (studentExamId,
                                                     questionId);

CREATE TABLE subject
(
    id           INTEGER NOT NULL,
    subject      VARCHAR2(512),
    name         VARCHAR2(3800),
    image        BLOB,
    sublectureId INTEGER NOT NULL
);

ALTER TABLE subject
    ADD CONSTRAINT subject_pk PRIMARY KEY (id);

CREATE TABLE sublecture
(
    id        INTEGER NOT NULL,
    title     VARCHAR2(128 CHAR),
    lectureId INTEGER NOT NULL
);

ALTER TABLE sublecture
    ADD CONSTRAINT sublecture_pk PRIMARY KEY (id);

CREATE TABLE test
(
    id             INTEGER NOT NULL,
    name           VARCHAR2(512 CHAR),
    numberQuestions INTEGER,
    image          BLOB,
    questionType   VARCHAR2(512 CHAR)
);

ALTER TABLE test
    ADD CONSTRAINT test_pk PRIMARY KEY (id);

CREATE TABLE userStatistic
(
    id           INTEGER NOT NULL,
    deposits     INTEGER,
    isExamPassed VARCHAR2(128 CHAR),
    hoursed     INTERVAL DAY (9) TO SECOND (0),
    hoursBuyed   INTERVAL DAY (9) TO SECOND (0),
    schoolUserId INTEGER NOT NULL
);

CREATE UNIQUE INDEX userstatistic__idx ON
    userStatistic (
                   schoolUserId
                   ASC);

ALTER TABLE userStatistic
    ADD CONSTRAINT userstatistic_pk PRIMARY KEY (id);

ALTER TABLE drivingSession
    ADD CONSTRAINT drivinglesson_schooluser_fk FOREIGN KEY (schoolUserId)
        REFERENCES schoolUser (id);

ALTER TABLE lectureMeeting
    ADD CONSTRAINT lecturemeeting_schooluser_fk FOREIGN KEY (schoolUserId)
        REFERENCES schoolUser (id)
        ON DELETE CASCADE;

ALTER TABLE payment
    ADD CONSTRAINT payment_schooluser_fk FOREIGN KEY (schoolUserId)
        REFERENCES schoolUser (id)
        ON DELETE CASCADE;

ALTER TABLE question
    ADD CONSTRAINT question_test_fk FOREIGN KEY (testId)
        REFERENCES test (id);

ALTER TABLE questionSet
    ADD CONSTRAINT questionset_exam_fk FOREIGN KEY (examId)
        REFERENCES exam (id);

ALTER TABLE questionSet
    ADD CONSTRAINT questionset_question_fk FOREIGN KEY (questionId)
        REFERENCES question (id);

ALTER TABLE sensitiveData
    ADD CONSTRAINT sensitivedata_schooluser_fk FOREIGN KEY (schoolUserId)
        REFERENCES schoolUser (id)
        ON DELETE CASCADE;

ALTER TABLE studentAnswersTest
    ADD CONSTRAINT studentanswerstest_question_fk FOREIGN KEY (questionId)
        REFERENCES question (id);

ALTER TABLE studentAnswersTest
    ADD CONSTRAINT studentanswerstest_su_fk FOREIGN KEY (schoolUserId)
        REFERENCES schoolUser (id)
        ON DELETE CASCADE;

ALTER TABLE studentAnswersTest
    ADD CONSTRAINT studentanswerstest_test_fk FOREIGN KEY (testId)
        REFERENCES test (id);

ALTER TABLE studentCourse
    ADD CONSTRAINT studentcourse_course_fk FOREIGN KEY (courseId)
        REFERENCES course (id);

ALTER TABLE studentCourse
    ADD CONSTRAINT studentcourse_schooluser_fk FOREIGN KEY (schoolUserId)
        REFERENCES schoolUser (id)
        ON DELETE CASCADE;

ALTER TABLE studentExam
    ADD CONSTRAINT studentexam_exam_fk FOREIGN KEY (examId)
        REFERENCES exam (id);

ALTER TABLE studentExam
    ADD CONSTRAINT studentexam_schooluser_fk FOREIGN KEY (schoolUserId)
        REFERENCES schoolUser (id)
        ON DELETE CASCADE;

ALTER TABLE studentExamAnswer
    ADD CONSTRAINT studentexamanswer_question_fk FOREIGN KEY (questionId)
        REFERENCES question (id);

ALTER TABLE studentExamAnswer
    ADD CONSTRAINT studentexamanswer_se_fk FOREIGN KEY (studentExamId)
        REFERENCES studentExam (id)
        ON DELETE CASCADE;

ALTER TABLE subject
    ADD CONSTRAINT subject_sublecture_fk FOREIGN KEY (sublectureId)
        REFERENCES sublecture (id)
        ON DELETE CASCADE;

ALTER TABLE sublecture
    ADD CONSTRAINT sublecture_lecture_fk FOREIGN KEY (lectureId)
        REFERENCES lecture (id)
        ON DELETE CASCADE;

ALTER TABLE userStatistic
    ADD CONSTRAINT userstatistic_schooluser_fk FOREIGN KEY (schoolUserId)
        REFERENCES schoolUser (id)
        ON DELETE CASCADE;



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            21
-- CREATE INDEX                             2
-- ALTER TABLE                             40
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
